pytest-dev/pytest-cov

pytest-cov/README.rst
I don't want my coverage reports to print on my CI targets, and using `--cov-report=html | xml` adds time overhead. This adds an option to suppress printing altogether. Let me know if this seems useful!
=> ENH: Allow silent operation

cov-core/cov_core.py
There may be cases where cov_core_init.init() returns None. 
Currently, multiprocessing_finish raises an AttributeError.
```
Traceback (most recent call last):
File "/..../lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
finalizer()
File "/.../lib/python2.7/multiprocessing/util.py", line 207, in __call__
res = self._callback(*self._args, **self._kwargs)
File "/.../lib/python2.7/site-packages/cov_core.py", line 19, in multiprocessing_finish
cov.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
```
It's a bit hard to reproduce with a unit test but i'm seeing the error when I run py.test with the `pytest-cov` plugin installed but not invoked
=> Remove MP Finalize if cov didnt initialize.

CHANGELOG.rst, src/pytest_cov/embed.py
(just like ``coverage.control.process_startup``).
Now that the `.pth` install works so well we can get these benign "No data was collected" warnings all over the plate. They are quite annoying if you do assertions on subprocess output.
=> Avoid warning about missing coverage data

docs/index.rst, docs/reference/index.rst, docs/reference/pytest_cover.rst, docs/releasing.rst, docs/usage.rst, tox.ini
Ref #60.
Post-release process intentionally left out. I need to check how easy is to "dev-bump" with bumpversion (eg: v1.2.3 to v1.2.4dev)
=> Remove placeholder pages and add a release process.

README.rst
Fixes an insecure content warning when viewing the package on PyPI e.g. https://pypi.python.org/pypi/pytest-cov
=> Use https for all badges

.bumpversion.cfg, setup.cfg, src/pytest_cov/embed.py, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py, tox.ini
These changes need a version later than 4.0b1 (the b1 release has this issue https://bitbucket.org/ned/coveragepy/issues/399/coverageexception-cant-combine-line-data). cc @The-Compiler
=> Coverage 4.0b2 support

src/pytest_cov/embed.py, src/pytest_cov/engine.py, tests/test_pytest_cov.py
Use absolute paths for coverage config file and sources. Add a new internal variable "COV_CORE_DATAFILE" to workaround the misplacement of .coverage.foobar.123 files.
Because needs to be an absolute path COV_CORE_CONFIG we need to do some special things: coverage treats config_file='.coveragerc' as if it was config_file=True. We need to keep that behavior.
Closes #94. Closes #77.
=> Fix handling when tests change working directory.

src/pytest_cov/engine.py, tests/test_pytest_cov.py
Add workaround for missing percentage total return from Coverage.annotate.
Also add missing test for --cov-report=annotate.
Closes #92.
=> Fix handling for --cov-report=annotate.

src/pytest_cov/engine.py, tests/test_pytest_cov.py
This affects xdist use with branch coverage measurements. Normal (line) coverage may be fine.
Gonna merge this soonish and make a new release if no comments.
(don't mind the coverage 4.1 failures)
=> Fix cov data merging

setup.py
3.5 is missing from the badge at https://github.com/pytest-dev/pytest-cov/blob/master/README.rst but looks like you support it.
=> Add Python 3.5 to setup.py

AUTHORS.rst, src/pytest_cov/plugin.py
See #108 for discussion. I was unsure of what exactly to add to the CHANGELOG so I let it be.
I looked into creating a fake test (ala pytest-pep8), but I was unsure how to implement this.
=> Correct hard fail with --cov-fail-under

src/pytest_cov/engine.py, tests/test_pytest_cov.py
This fixes lack of coverage measurements when covered module is out of CWD and `--cov=module` was used.
(only affects suprocess measurements)
=> Dont absolutize source path

AUTHORS.rst, CHANGELOG.rst, README.rst, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
Add support for specifying output location for html, xml, and annotate report. Fixes issue #97.
=> Specify file output

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/compat.py, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
don't hide failed tests when cov-fail-under fails
c.f. #108 
also tweaks failure semantics slightly, see changelog (hence minor version bump)
=> Show errors on insufficient cov

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
`pytest-cov` used to fail on such parameters combination:
```bash
py.test --cov -n1
```
I've added small fixup of `cov_source` parameter, if empty `--cov` is used.
Closes #110
=> Dont fail on xdist with bare --cov

AUTHORS.rst, CHANGELOG.rst, README.rst, setup.cfg, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
This is a working implementation and works fine with `.coveragerc` and `setup.cfg`.
I've not added relevant docs and test, as i'm still trying to understand those. 
@ionelmc if this looks good, i'll try to add docs and tests. 
Ref: http://coverage.readthedocs.io/en/latest/api_coverage.html#coverage.Coverage.report
closes #114
=> Add support for 'skip_covered' option in terminal report section

src/pytest_cov/plugin.py
With pytest 3.0 (not released yet) the following warning gets emitted:
> WC1 None pytest_funcarg__cov: declaring fixtures using
> "pytest_funcarg__" prefix is deprecated and scheduled to be removed in
> pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator
> instead.
=> Fix definition of `cov` fixture for pytest 3

src/pytest_cov/plugin.py
Otherwise we get this DeprecationWarning with pytest 3.0:
[...]
File ".../pytest_cov/plugin.py", line 72, in pytest_addoption
help='Fail if the total coverage is less than MIN.')
File ".../_pytest/config.py", line 482, in addoption
self._anonymous.addoption(*opts, **attrs)
File ".../_pytest/config.py", line 708, in addoption
option = Argument(*optnames, **attrs)
File ".../_pytest/config.py", line 609, in __init__
stacklevel=3)
DeprecationWarning: type argument to addoption() is a string 'int'. For parsearg this should be a type. (options: ('--cov-fail-under',))
=> Pass a type instead of string to parser.addoption

README.rst, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
Please let me know what you think.
=> Implementing no_cov feature for #131

setup.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
This pr is the updated version of #140.
In our case, we specify `--cov-report=html` and `--cov-fail-under=85`, we want to see the total coverage in CI console at a glance, instead of printing a full term report or opening the html report, even when required test coverage(85%) is reached. So if total coverage is close to required, we may take actions in advance.
=> show total coverage when required test coverage reached

src/pytest_cov/plugin.py
`--cov-report=` to not output any error is hard to guess.
=> Fix and improve help for --cov-report

src/pytest_cov/engine.py, tests/test_pytest_cov.py
=> Get data_file path from Coverage config in subprocesses.

docs/plugins.rst
A colon was missing so the code block was no code block, but a quote.
=> Fix typo in plugin docu

.travis.yml
Python 3.7 was added to the test matrix in https://github.com/pytest-dev/pytest-cov/commit/3cf7f73488e81d0ed5b30ef19ab85c41b9a9a7af.
However, the 3.7 builds are failing as it requires Xenial and sudo. 
Let's enable those for just the 3.7 builds.
See https://github.com/travis-ci/travis-ci/issues/9815 for more info.
---
By the way, do you know roughly when the next release will be?
=> Travis CI: Python 3.7 requires Xenial and sudo

src/pytest_cov/engine.py, tests/test_pytest_cov.py
Although you can normally use `--cov` without an argument to read the modules to be covered from `.coveragerc`, this currently doesn't work for non-collocated xdist workers because the code doesn't account for the possibility that `self.cov_source` is `None`:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "_pytest/main.py", line 176, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec …
```
=> Allow remote nodes to get source modules from .coveragerc

tests/test_pytest_cov.py
It does not seem to be necessary.
Found while looking into https://github.com/pytest-dev/pytest-cov/issues/204.
=> tests: test_central_subprocess_no_subscript: remove omit

docs/config.rst
It took me some time to figure out how to have pytest-cov be run automatically with pytest when I switched to a 100% conf-file (personally I used `setup.cfg`) driven testing.
I think an example in the docs would be helpful and non-invasive.
Open to different wordings.
I didn't add myself into the `AUTHORS.rst` as I don't believe this is anywhere near authoring work.
Regards!
=> Added in the doc a useful example to help integrate pytest-cov.

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py
fixes regression in a02e1c83a273517dd82ef638cbb7717e5f52bbc9 (#78) which makes `pytest --cov` not friendly with `pytest --doctest-modules`
=> fix DoctestItem has no attribute fixturenames

src/pytest_cov/plugin.py
`config.warn` and `node.warn` were deprecated in pytest 3.8: 
https://docs.pytest.org/en/latest/deprecations.html#config-warn-and-node-warn
=> Don't use deprecated config.warn

src/pytest_cov/__init__.py
> Module already imported so cannot be rewritten
Fixes https://github.com/pytest-dev/pytest-cov/issues/211
=> Avoid "Module already imported" warning from pytest

tests/test_pytest_cov.py
Pytest 3.9.0 introduced a timeout for ``Testdir.runpytest_subprocess()``
and ``Testdir.run()``. So API has been changed and now it looks like
``run(self, *cmdargs, **kwargs)``.
Hence to comply with the new API it needs to fix a lambda's definition.
Fixes: https://github.com/pytest-dev/pytest-cov/issues/247
Signed-off-by: Stanislav Levin <slev@altlinux.org>
=> Fix test_cover_looponfail test

setup.py, src/pytest_cov/plugin.py
Fixes pytest-cov with pytest 4.1.
Requires pytest 3.6+ now.
=> Use get_closest_marker

docs/plugins.rst
Without `--cov` pytest-cov will not track coverage at all.
[ci skip]
=> docs/plugins.rst: use --cov with addopts

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
1. Install `pytest-cov` and `pytest-xdist`
2. Make file `test_cov.py`:
```(python)
def test_cov():
assert 1 == 1
```
3. Make file `setup.cfg`:
```
[tool:pytest]
addopts =
--cov=.
```
4. Run `pytest --no-cov -n 2`:
```
==================================================================================================================== test session starts ====================================================================================================================
platform linux2 -- Python 2.7.12, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/shadchin/tets_cov, inifile: setup.cfg
plugins: xdist-1.26.1, forked-1.0.1, cov-2.6.1
gw0 C / gw1 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/shadchin/tets_cov/venv/local/lib/python2.7/site-packages/_pytest/ …
```
=> Skip hook if cov disabled

tox.ini
The typical use case is pass args to pytest, not change the executable
(pytest) itself:
> tox -e … -- -k foo
=> tox.ini: do not use "pytest" inside of "{posargs}"

src/pytest_cov/embed.py, tests/test_pytest_cov.py, tox.ini
=> Improve cleanup_on_sigterm

setup.py
This was accidentally reverted/lost in a5a1f61, and is required for
AppVeyor.
=> reqs: testing: use process-tests==2.0.2 again

setup.cfg, tests/test_pytest_cov.py, tox.ini
Fixes https://github.com/pytest-dev/pytest-cov/issues/270.
=> tests: set PYTHONPATH via session scoped fixture

src/pytest_cov/plugin.py
Currently running `pytest --fixtures` in a project using pytest-cov returns an ugly:
```bash
no_cover
.../pytest_cov/plugin.py:306: no docstring available
```
This PR fix that.
=> Add docstring to no_cover fixture

tests/test_pytest_cov.py
One test is asserting that "coverage" doesn't appear in the output. But I cloned this repo into "~/coverage/pytest-cov" so the word appears.  I tweaked the test to prevent a misdiagnosis.
The failing test was this:
```
______________________________________________________________________________________ test_disabled_output ______________________________________________________________________________________
/Users/ned/coverage/pytest-cov/tests/test_pytest_cov.py:1661: in test_disabled_output
assert 'coverage' not in result.stdout.str()
E   AssertionError: assert 'coverage' not in '=====================...====================='
E     'coverage' is contained here:
E       ============================= test session starts ==============================
E       platform darwin -- Python …
```
=> Don't be fooled by "coverage" in a path.

tox.ini
This uses internal env vars for deps, allowing to install them always
(unpinned).
=> tox.ini: make "tox -e pypy" etc work

tests/test_pytest_cov.py
Asserting the return value first helps in case it is 120 due to
Coverage.py not being installed correctly.
Ref: https://github.com/pytest-dev/pytest-cov/pull/319#issuecomment-522341601
=> minor: improve test_dist_missing_data: doc, assert ret first

src/pytest_cov/plugin.py, tests/test_pytest_cov.py
It only show the decimal part if needed. Fix #260.
=> Support float values for --cov-fail-under.

tox.ini
Otherwise tests will fail currently, e.g.
`tox -e py37 -- tests/test_pytest_cov.py::test_dist_missing_data`
=> tox.ini: default to Coverage.py < 5

.travis.yml, appveyor.yml, ci/bootstrap.py, ci/templates/.travis.yml, ci/templates/appveyor.yml, src/pytest_cov/embed.py, tests/test_pytest_cov.py, tox.ini
Also test py3.6, 3.7 and pypy3 on Appveyor.
=> Update test deps

examples/adhoc-layout/example/__init__.py, examples/src-layout/src/example/__init__.py
We don't yet know if 3.10 or 4.0 will follow Python 3.9, but whichever it is, it will probably happen in [2020 when Python 3.9 reaches beta](https://www.python.org/dev/peps/pep-0596/#schedule) and work begins on Python 3.9+1.
Some examples are like this:
```python
PY3 = sys.version_info[0] == 3
if PY3:
print("Python 3+ code")
else:
print("Python 2 code")
```
When run on Python 4, this will run the Python 2 code! Instead, use `PY2`.
Found using https://github.com/asottile/flake8-2020:
```console
$ pip install -U flake8-2020
...
$ flake8 --select YTT
./examples/src-layout/src/example/__init__.py:4:7: YTT201 `sys.version_info[0] == 3` referenced (python4), use `>=`
./examples/adhoc-layout/example/__init__.py:4:7: YTT201 `sys.version_info[0] == 3` referenced (python4), use `>=`
```
=> Fix for Python 4: replace unsafe PY3 with PY2

.travis.yml, appveyor.yml, src/pytest_cov/engine.py, tests/test_pytest_cov.py, tox.ini
Add support for coverage 5.0, while keeping 4.5.x working.
Looking for feedback about the approach, and help with still-failing tests.
=> Support for coverage 5.0

.travis.yml, AUTHORS.rst, CHANGELOG.rst, appveyor.yml, docs/config.rst, docs/contexts.rst, docs/index.rst, setup.py, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/contextful.py, tests/test_pytest_cov.py, tox.ini
This is #342 rebased with a couple changes.
`--cov-context` vs `--cov-contexts` - what's better?
=> Dynamic contexts

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py
With the current code, introduced in #230, the comparison
`pytest.__version__ >= '3.8'` returns the wrong result when using
PyTest 3.10, as `'3.10' < '3.8'` if we use Python's string comparison.
Having `PYTEST_VERSION` as an integer tuple allows us to have simpler
comparisons.
This fixes the following warning when using PyTest 3.10:
```
RemovedInPytest4Warning: config.warn has been deprecated, use warnings.warn instead
```
=> Fix comparison against installed PyTest version

setup.py
Tests require it currently, and it is not trivial to make it optional.
=> setup.py: "testing" extras_require: add pytest-xdist

setup.cfg
It silently ignores `-l` etc, and should be used on-demand only.
Ref: https://github.com/pytest-dev/pytest/issues/494
=> setup.cfg: do not use --tb=short by default

.travis.yml, appveyor.yml, ci/templates/appveyor.yml, docs/releasing.rst, setup.py, tox.ini
Python  3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16
* https://en.wikipedia.org/wiki/CPython#Version_history
The latest pytest 5.x series has dropped 3.4 (and 2.7):
* https://pytest.org/en/latest/py27-py34-deprecation.html
There's not a huge amount of code changes from dropping 3.4, but the biggest benefit is reducing the build matrix, which is currently a hefty 34 jobs and 30+ minutes.
=> Drop support for EOL Python 3.4

.travis.yml, ci/templates/.travis.yml
And don't allow it to fail.
These are currently failing/erroring, as they are on `master`. Those that I checked were doing so in the same way in this PR and on `master` (as expected).
=> Travis CI: Test on Python 3.8 final

tests/test_pytest_cov.py, tox.ini
but it was because the test was fragile.  This fixes the test.
=> The context tests were failing on newer coverage

.travis.yml, appveyor.yml, ci/templates/.travis.yml, docs/requirements.txt, examples/adhoc-layout/tox.ini, examples/src-layout/tox.ini, tests/test_pytest_cov.py, tox.ini
Closes #365.
Similar to the reasoning in #182, I'd like to suggest reducing the build matrix.
There are now 76 jobs (only looking at Travis CI), testing 8 Python versions against 4 pytest versions (spanning 3 major pytest releases), 4 xdist versions and 2 Coverage.py versions.
* Is it really necessary to test against all those old versions?
* Does pytest-cov need to make promises to support old releases?
* Do those projects promise to support so many old releases, or just the most recent?
Further, some two dozen of the build jobs are failing, giving less confidence in the CI/tests as a whole.
https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix says:
> *All build matrixes are currently limited to a maximum of* **200 JOBS** *for both private and public repositories. If you …
=> Reduce test matrix

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py
This saves me ~0.1s when running tests without coverage where this plugin is installed.
=> Avoid importing coverage for test runs that don't need it

setup.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
Only do it if --no-cov is present before --cov. Also remove some legacy pytest support and bump min version in setup.py. Closes #407. Ref #304.
=> Implement better --no-cov warning

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/compat.py, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
Fixes #411, at cost of support for xdist 1.22 and earlier from 2017.  Given that such old versions aren't even in our test matrix, I figured that this would be OK.
=> Use "worker" for compatibility with xdist >= 2.0

CHANGELOG.rst
Python < 3.4 was not dropped in 2.6.0, as Python 2.7 is still supported. Fix this changelog typo to make things clear
=> Python 2 has not been dropped yet

docs/config.rst
I took a while to figure out why coverage wasn't working correctly for our large project until yesterday, when I read the paragraph that called out the `.coveragerc` options that `pytest-cov` ignores.  
This PR makes that part of the documentation "pop" a bit more.
I considered moving it under "Caveats", but decided that that would mean rewriting "Caveats" to have two separate issues, rather than the one that it currently explains.
=> Update config.rst wrt ignored .coveragerc settings

src/pytest_cov/embed.py, src/pytest_cov/engine.py, src/pytest_cov/plugin.py
At the moment subprocess calls are missing coverage context, this fixes that issue.
Resolves #442 
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
=> Inherit coverage context in subprocesses

setup.py
The empty 'console_scripts' entry point serves no purpose, and it is
rather unlikely for it to contain any script in the near future.  Its
presence confuses Gentoo missing dependency checks.
=> Do not install empty console_scripts entry point

examples/adhoc-layout/tox.ini, examples/src-layout/tox.ini
`tox -e pyXX` does not run the envs that pyXX depends on [[src](https://tox.readthedocs.io/en/latest/config.html?highlight=depends#conf-depends)]. This means that with the current example configs, running `tox -e pyXX` will not run `coverage clean` and so `pytest-cov` data will be appended to the preexisting `.coverage` file.
IMO, appending to the existing coverage data is not the expected behavior when running a single test suite against one Python version.
In fact, the current behavior can even cause decreased coverage to go undetected. E.g.:
1.  The user runs `tox` and generates a `.coverage` file that reports 100% coverage.
1.  The user deletes a bunch of tests and then runs `tox -e py38`.
With the current example configs, `tox -e py38` will report 100% coverage despite coverage …
=> Change example configs to support tox -e pyXX

setup.py
Possible solution to issue #409. Code coverage report included lines that don't exist on python 3.8.5 and coverage 4.4. Example repo [NovaAPI](https://github.com/novaweb-mobi/nova-api). Updating coverage solved the issue.
fixes #409
=> Bumped coverage to 5.2.1

setup.py
Fix custom commands to handle additional arguments to the run() method.
This is needed with newer versions of setuptools since they've started
passing 'show_deprecation' kwarg in easy_install command, and this
resulted in the following error:
```
Traceback (most recent call last):
File "/tmp/pytest-cov/./setup.py", line 86, in <module>
setup(
File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", …
```
=> Fix custom setup.py commands with newer setuptools

setup.py
License listed in setup.py says BSD while LICENSE file says MIT.
This led some tools  for license check to incorrectly state that the license for pytest-cov is BSD.
Changing setup.py license from BSD to MIT to correct this.
=> change license in setup.py from BSD to MIT to match LICENSE file

docs/contexts.rst
Fixes #469, related to #371.
FYI @nedbat @dkotschessa
=> Document `show_contexts`

setup.py
Avoid pip-compile bug which forces it to produce invalid constraints files. Installing toml as a direct dependency is enough to avoid this bug as fixing it in pip-compile is far from an easy task.
Declaring dependencies using extras is a extremely uncommon in python packages and as far as I know this is the only mainstream package that does that, and is is very easy to avoid. If we not fixing this we prevent users from creating constraints for their test requirements, something very useful as nobody likes getting its CI broken due to some test tool being updated an hour ago.
Related: https://github.com/jazzband/pip-tools/issues/1300
=> Avoid using toml as extra

docs/contexts.rst
The hyperlink wasn't rendering properly. This looks better.
=> Fix typo in contexts.rst

setup.py
This reverts commit 34edfa1cf80f8d722dec4f587b10d2783f89a0f0.
coverage[toml] now depends on `tomli`: https://github.com/nedbat/coveragepy/blob/c0da97eb03d4ffe8be8854ad6ff1a2736f169003/setup.py#L110
and this is fixed now https://github.com/jazzband/pip-tools/issues/1300
so I think the work-around should be removed
=> Revert "Avoid using toml as extra (#472)"

.github/workflows/test.yml, setup.cfg, setup.py, tox.ini
Ahead of tomorrow's release party! https://twitter.com/pyblogsal/status/1442890650303664131
Bumps the pinned version of pytest 6.2, needed to support Python 3.10.
Also no need to build universal wheels for Python 3-only.
=> Add support for Python 3.10

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
I often have `--cov-fail-under=100` set from a config file, because I expect full coverage from running my tests.
With [HypoFuzz](https://pypi.org/project/hypofuzz/), however, I use `pytest --collect-only` to collect the tests and then run them with the fuzzer... but `--cov-fail-under` returns an error because collection didn't reach 100% coverage!  That seems pretty silly, so this patch makes us skip the coverage check if pytest is running in `--collect-only` mode.  Fixes #426. 
(I can `hypothesis fuzz -- --cov-fail-under=0` for now, but that's a pretty inelegant workaround which I'd rather not require of my users)
=> `--cov-fail-under` should not cause `pytest --collect-only` to fail

CHANGELOG.rst
I got confused when I updated to `3.0.0` and still saw `coverage[toml]` in my requirements....
=> Update Changelog to reflect toml requirement change

tests/test_pytest_cov.py
Update test_invalid_coverage_source to make the "No data was collected"
less strict, as the output has changed in coverage-6.2.  This solution
was suggested by Tom Callaway (@spotrh) on the linked bug.
Fixes #509
=> Update test_invalid_coverage_source for coverage-6.2

docs/debuggers.rst
This PR adds a specific error message a user might encounter when debugging tests with code coverage enabled.
I experienced this issue today and unfortunately could not easily locate this documentation page.  I had to follow many different breadcrumb trails to get here.  Hopefully by adding this to the documentation future developers can more easily locate this documentation, understand the problem, and use the `--no-cov` flag to avoid it.
=> Add sample error a user might encounter

setup.py
Importing distutils before setuptools can (depending on the precendence of the current import search path) create problems:
```
[   19s] + cd pytest-cov-3.0.0
[   19s] + /usr/bin/python3.8 setup.py build '--executable=/usr/bin/python3.8 -s'
[   19s] /usr/lib/python3.8/site-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
[   19s]   warnings.warn(
[   19s] …
```
=> migrate build command from distutils to setuptools

src/pytest_cov/plugin.py
Hi!
This is just a small tweak so that report displayed when `--cov-report=` matches the default `pytest` output. Otherwise, undesirable newlines are added while the output is empty anyway.
Before:
```
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/delgan/Programmation/loguru, configfile: tox.ini
plugins: cov-3.0.0, mypy-plugins-1.9.3
collected 1425 items / 1424 deselected / 1 selected                                                                                                                             
tests/test_levels.py . …
```
=> Prevent undesirable new lines to be displayed when report is disabled

AUTHORS.rst, CHANGELOG.rst, docs/config.rst, docs/reporting.rst, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
Coverage.py 6.3 gained support for the LCOV output format. Add support for this to *pytest-cov* via `--cov-report=lcov[:dest]`.
Fix: #535
My main motivation was that coveralls currently only supports LCOV in their [GitHub Action](https://github.com/coverallsapp/github-action/issues/30). But since LCOV is a widely adopted format I think there might be more benefits of adding this to *pytest-cov*.
I've tried to follow [CONTRIBUTING.rst](https://github.com/pytest-dev/pytest-cov/blob/master/CONTRIBUTING.rst), let me know if you want me to add/change anything.
~*Update:* The second commit is unrelated, but fixes the check pipeline.~
=> Add support for LCOV output

setup.py
https://github.com/nedbat/coveragepy/issues/664 (+ later fixes)
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
=> Enable `pytest-cov[toml]` akin to upstream `coverage[toml]`

setup.py
Reverts pytest-dev/pytest-cov#553
=> Revert "Enable `pytest-cov[toml]` akin to upstream `coverage[toml]`"

.github/workflows/test.yml, .pre-commit-config.yaml, ci/bootstrap.py, setup.py, tests/test_pytest_cov.py, tox.ini
* https://github.com/actions/cache/releases
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
* https://docs.python.org/3/whatsnew/3.11.html
* https://www.pypy.org/download.html
=> Add Python 3.11 and PyPy 3.9 to the testing and drop 3.6

src/pytest_cov/engine.py
=> Remove use of rsyncdir

AUTHORS.rst, CHANGELOG.rst, src/pytest_cov/plugin.py
👋 I would like to propose a small change to the control flow which precludes generating the coverage report if it is not going to be used by the given pytest run in which it was generated (i.e. it is going to be combined with other reports later).
I didn't add any new tests yet because I don't see any observable difference from the perspective of the tests. If there's any suggestions on how to support this change with a test, I'm happy to add tests to verify the behavior.
Waaay back when #34 was merged, the control flow changed to always generate a coverage report, even if it isn't used.
On small code bases, or code bases that collect all of their coverage in one step, this is probably fine, but on large code bases, it can take minutes to generate the report.
When used in conjunction with …
=> perf: only call summary when the report will be used

docs/config.rst
* Clarify that existing instructions are for `setup.cfg`
* Add a corresponding example for `pyproject.toml`
=> docs: add config instructions for pyproject.toml.

.pre-commit-config.yaml, pyproject.toml, src/pytest_cov/engine.py, src/pytest_cov/plugin.py
Following up on `ruff` being added for linting in #610, this makes formatting also use `ruff` instead of Black.
=> Use ruff for formatting too

tests/test_pytest_cov.py
Coverage 7.5 now writes out two other files when generating a HTML report -- class_index and function_index. We check explicitly for which files have been written, so add those two in if coverage is >= 7.5.
=> Support Coverage 7.5's HTML report changes

src/pytest_cov/__init__.py, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
=> Handle issue 604

CHANGELOG.rst
This should make it a bit easier for devs to handle updating old projects.
=> Update CHANGELOG.rst to highlight when python 3.7 and 3.6 where dropped

AUTHORS.rst, docs/conf.py
as suggested in #678 
**Edit**:
This PR addresses issues related to the Sphinx link checker and updates outdated links to resolve failing tests.
Changes Made
1. Link Check Configuration:
GitHub has changed the way anchors are injected into web pages, causing the Sphinx link checker to fail. This configuration update allows us to skip anchor checking for GitHub URLs, preventing unnecessary build failures.
2. Updated Links:
The http://firelet.net URL is no longer accessible, causing Sphinx's link checker to generate build errors. Adjusted to conform with others in the file that are escaped with backslashes.
=> fix failing tests related to broken links

src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
This PR improves the formatting of separator lines in coverage reports and enhances the robustness of terminal width handling.
- To conform to the visuals from pytest headings.
- To allow clear separation of this plugin output from the previous section
- Add a new section heading for the coverage tests output.
- Make all headings the same width as pytest's headings.
- Change separator character of regular headings from `-` to `_`.
=> Improve Terminal Output Formatting in pytest-cov

CHANGELOG.rst, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
=> Allow the context plugin to check if the controller is running or not.

docs/conf.py
Fixed the `html_theme_options` in config file since the option `githuburl` is not supported.
(ref: https://pradyunsg.me/furo/customisation/top-of-page-buttons/#with-popular-vcs-hosts .)
Now the "view/edit" buttons (on the top right) correctly point to the github repository.
=> Fix document theme parameter in sphinx config file

CONTRIBUTING.rst, README.rst, docs/config.rst
Incorrect indents cause some texts to be misinterpreted as blockquotes and render incorrectly.
=> Remove some extra indents in documentation

AUTHORS.rst, docs/config.rst, docs/reporting.rst, src/pytest_cov/engine.py, src/pytest_cov/plugin.py, tests/test_pytest_cov.py
Closes https://github.com/pytest-dev/pytest-cov/issues/688
Option which implements markdown support as a file_choice.
We would diverge a bit from the Coverage.py API, creating our own sort of behavior for the `markdown` option. But might be useful indeed.
Example output:
File generated:
=> Adding Markdown support as a file_choice
